language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - pypy3
install:
  - python setup.py install
script:
  - python -m mypy bpe --ignore-missing-imports
  - python -m mypy bpe --py2 --ignore-missing-imports
  - python setup.py test
